import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";
import TitleHeader from "@/components/titles/TitleHeader";
import LenisScroll from "@/components/lenisScroll/LenisScroll";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className="relative"> 
      <LenisScroll >
        {/* <div className=" z-50 pl-10 w-full bg-transparent">
          <TitleHeader />
        </div> */}
        
          <Header /> 
        
        {children}
        
      </LenisScroll>
      </body>
    </html>
  );
}
